CREATE TABLE weather_fact (
    weather_id INT AUTO_INCREMENT PRIMARY KEY,
    date_key INT NOT NULL,
    wind_key INT NOT NULL,
    temp DECIMAL(5, 2) NOT NULL,
    feelslike DECIMAL(5, 2) NOT NULL,
    dew DECIMAL(5, 2) NOT NULL,
    humidity DECIMAL(5, 2) NOT NULL,
    precip DECIMAL(5, 2) NOT NULL,
    precipprob INT NOT NULL,
    preciptype VARCHAR(50),
    snow DECIMAL(5, 2) NOT NULL,
    snowdepth DECIMAL(5, 2) NOT NULL,
    sealevelpressure DECIMAL(6, 2) NOT NULL,
    cloudcover DECIMAL(5, 2) NOT NULL,
    visibility DECIMAL(5, 2) NOT NULL,
    solarradiation DECIMAL(5, 2),
    solarenergy DECIMAL(5, 2),
    uvindex INT,
    severerisk INT NOT NULL,
    conditions VARCHAR(255) NOT NULL,
    icon VARCHAR(50),
    stations VARCHAR(255),
    CONSTRAINT fk_weather_date FOREIGN KEY (date_key) REFERENCES date_dimension(date_key),
    CONSTRAINT fk_weather_wind FOREIGN KEY (wind_key) REFERENCES wind_dimension(wind_key)
);